version: "3.8"

services:
  ### Web App (React + .NET Core API)
  heroscapebuilder:
    image: heroscapebuilder:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+
      - HeroscapeBuilder=${HeroscapeBuilder}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == projectmaster
    networks:
      - internal_network

  ### MinIO Storage Service - Node 1
  minio1:
    image: minio/minio
    hostname: minio1
    command: server --address ":9000" --console-address ":9081" http://minio1/data1 http://minio2/data2
    environment:
      - MINIO_ROOT_USER=5Y5aCgFi@SF7!dMeMlJ$$
      - MINIO_ROOT_PASSWORD=K@VW7s$$!r6bj&fC57rMtqy3v9sVA$$3v^gNbbsh4R
      - MINIO_DISTRIBUTED_MODE_ENABLED="yes"
      - MINIO_DISTRIBUTED_NODES=minio1,minio2
      - MINIO_SERVER_URL=http://heroscapebuilder.com/file
    volumes:
      - /mnt/minio_storage/data1:/data1
    networks:
      - internal_network
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == projectmaster
    ports:
      - "2096:9000"
      - "9081:9081"

  ### MinIO Storage Service - Node 2
  minio2:
    image: minio/minio
    hostname: minio2
    command: server --address ":9000" --console-address ":9081" http://minio1/data1 http://minio2/data2
    environment:
      - MINIO_ROOT_USER=5Y5aCgFi@SF7!dMeMlJ$$
      - MINIO_ROOT_PASSWORD=K@VW7s$$!r6bj&fC57rMtqy3v9sVA$$3v^gNbbsh4R
      - MINIO_DISTRIBUTED_MODE_ENABLED="yes"
      - MINIO_DISTRIBUTED_NODES=minio1,minio2
      - MINIO_SERVER_URL=http://heroscapebuilder.com/file
    volumes:
      - /mnt/minio_storage/data2:/data2
    networks:
      - internal_network
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == elitedesk
    ports:
      - "2097:9000"
      - "9082:9081"

  ### Nginx Reverse Proxy for MinIO
  nginx:
    image: nginx
    volumes:
      - /nginx.conf:/etc/nginx/nginx.conf:ro
      - /heroscapebuilder-certs:/certs
    ports:
      - "8012:80"
      - "8043:443"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == projectmaster
    networks:
      - internal_network


networks:
  internal_network:
    driver: overlay
    attachable: true
