version: "3.8"

services:
  ### Web App (React + .NET Core API)
  heroscapebuilder:
    image: abnoba12/heroscapebuilder
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+
      - HeroscapeBuilder=${HeroscapeBuilder}
    deploy:
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1
    networks:
      - internal_network
      
  minio:
    image: minio/minio:latest
    command: server --address ":9000" --console-address ":9081" /data
    environment:
      MINIO_ROOT_USER: Hassle864
      MINIO_ROOT_PASSWORD: 6vMAidQ4RvYRSJJ5yg5FAgAJgi3Hi2
      MINIO_SERVER_URL: "http://files.heroscapebuilder.com"
      MINIO_BROWSER_REDIRECT_URL: "http://minio-console.local"
      MINIO_UPLOAD_PART_SIZE: 1G
      MINIO_MAX_OBJECT_SIZE: 1G
    volumes:
      - /home/abnoba12/Sync/minio_storage/data:/data
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - target: 9000
        published: 2096
        protocol: tcp
      - target: 9081
        published: 9081
        protocol: tcp
    networks:
      - internal_network

  ### Nginx Reverse Proxy for MinIO
  nginx:
    image: nginx
    volumes:
      - /home/abnoba12/Sync/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/abnoba12/Sync/heroscapebuilder-certs:/certs
    ports:
      - "8012:80"
      - "8043:443"
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == projectmaster
    networks:
      - internal_network

networks:
  internal_network:
    driver: overlay
    attachable: true
