// <auto-generated />
using System;
using HeroscapeBuilder.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeroscapeBuilder.Server.Data.Migrations
{
    [DbContext(typeof(HsbDbContext))]
    [Migration("20241120203207_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.ArmyCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("AdvAttack")
                        .HasColumnType("bigint");

                    b.Property<long?>("AdvDefense")
                        .HasColumnType("bigint");

                    b.Property<long?>("AdvMove")
                        .HasColumnType("bigint");

                    b.Property<long?>("AdvRange")
                        .HasColumnType("bigint");

                    b.Property<long?>("BasicAttack")
                        .HasColumnType("bigint");

                    b.Property<long?>("BasicDefense")
                        .HasColumnType("bigint");

                    b.Property<long?>("BasicMove")
                        .HasColumnType("bigint");

                    b.Property<long?>("BasicRange")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("General")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Life")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Planet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Points")
                        .HasColumnType("bigint");

                    b.Property<string>("Race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rarity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STL_File")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Set")
                        .HasColumnType("bigint");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("SizeCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("army_card_pkey");

                    b.HasIndex("Creator");

                    b.HasIndex("Set");

                    b.ToTable("army_card", null, t =>
                        {
                            t.HasComment("A list of stats and abilities for each unit in Heroscape");
                        });
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.ArmyCardAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ability");

                    b.Property<string>("AbilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ability_name");

                    b.Property<int>("ArmyCardId")
                        .HasColumnType("int")
                        .HasColumnName("army_card_id");

                    b.HasKey("Id")
                        .HasName("army_card_abilites_pkey");

                    b.HasIndex("ArmyCardId");

                    b.ToTable("army_card_abilities", (string)null);
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.ArmyCardFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ArmyCardId")
                        .HasColumnType("int")
                        .HasColumnName("army_card_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_path");

                    b.Property<string>("FilePurpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_purpose");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent");

                    b.HasKey("Id")
                        .HasName("army_card_files_pkey");

                    b.HasIndex("ArmyCardId");

                    b.HasIndex("ParentId");

                    b.ToTable("army_card_files", (string)null);
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.Creator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatorName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Creator");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id", "CreatorName")
                        .HasName("Creator_pkey");

                    b.HasIndex(new[] { "CreatorName" }, "Creator_Creator_key")
                        .IsUnique();

                    b.ToTable("creator", (string)null);
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.Set", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("Heroscape")
                        .HasColumnName("creator");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<long?>("UnitsInSet")
                        .HasColumnType("bigint")
                        .HasColumnName("units_in_set");

                    b.Property<string>("Wave")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("wave");

                    b.HasKey("Id")
                        .HasName("set_pkey");

                    b.HasIndex("Creator");

                    b.ToTable("set", (string)null);
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.SetTerrain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint")
                        .HasColumnName("quantity");

                    b.Property<long>("Set")
                        .HasColumnType("bigint")
                        .HasColumnName("set");

                    b.Property<long>("Terrain")
                        .HasColumnType("bigint")
                        .HasColumnName("terrain");

                    b.HasKey("Id")
                        .HasName("set_terrain_pkey");

                    b.HasIndex("Set");

                    b.HasIndex("Terrain");

                    b.ToTable("set_terrain", (string)null);
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.Terrain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short?>("Hexes")
                        .HasColumnType("smallint")
                        .HasColumnName("hexes");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("terrain_pkey");

                    b.ToTable("terrain", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.ArmyCard", b =>
                {
                    b.HasOne("HeroscapeBuilder.Server.Data.Entities.Creator", "CreatorNavigation")
                        .WithMany("ArmyCards")
                        .HasForeignKey("Creator")
                        .HasPrincipalKey("CreatorName")
                        .IsRequired()
                        .HasConstraintName("army_card_Creator_fkey");

                    b.HasOne("HeroscapeBuilder.Server.Data.Entities.Set", "SetNavigation")
                        .WithMany("ArmyCards")
                        .HasForeignKey("Set")
                        .HasConstraintName("army_card_Set_fkey");

                    b.Navigation("CreatorNavigation");

                    b.Navigation("SetNavigation");
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.ArmyCardAbility", b =>
                {
                    b.HasOne("HeroscapeBuilder.Server.Data.Entities.ArmyCard", "ArmyCard")
                        .WithMany("ArmyCardAbilities")
                        .HasForeignKey("ArmyCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("army_card_abilities_army_card_id_fkey");

                    b.Navigation("ArmyCard");
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.ArmyCardFile", b =>
                {
                    b.HasOne("HeroscapeBuilder.Server.Data.Entities.ArmyCard", "ArmyCard")
                        .WithMany("ArmyCardFiles")
                        .HasForeignKey("ArmyCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("army_card_files_army_card_id_fkey");

                    b.HasOne("HeroscapeBuilder.Server.Data.Entities.ArmyCardFile", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("army_card_files_parent_fkey");

                    b.Navigation("ArmyCard");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.Set", b =>
                {
                    b.HasOne("HeroscapeBuilder.Server.Data.Entities.Creator", "CreatorNavigation")
                        .WithMany("Sets")
                        .HasForeignKey("Creator")
                        .HasPrincipalKey("CreatorName")
                        .IsRequired()
                        .HasConstraintName("set_creator_fkey");

                    b.Navigation("CreatorNavigation");
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.SetTerrain", b =>
                {
                    b.HasOne("HeroscapeBuilder.Server.Data.Entities.Set", "SetNavigation")
                        .WithMany("SetTerrains")
                        .HasForeignKey("Set")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("set_terrain_set_fkey");

                    b.HasOne("HeroscapeBuilder.Server.Data.Entities.Terrain", "TerrainNavigation")
                        .WithMany("SetTerrains")
                        .HasForeignKey("Terrain")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("set_terrain_terrain_fkey");

                    b.Navigation("SetNavigation");

                    b.Navigation("TerrainNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.ArmyCard", b =>
                {
                    b.Navigation("ArmyCardAbilities");

                    b.Navigation("ArmyCardFiles");
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.ArmyCardFile", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.Creator", b =>
                {
                    b.Navigation("ArmyCards");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.Set", b =>
                {
                    b.Navigation("ArmyCards");

                    b.Navigation("SetTerrains");
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.Terrain", b =>
                {
                    b.Navigation("SetTerrains");
                });
#pragma warning restore 612, 618
        }
    }
}
