// <auto-generated />
using System;
using HeroscapeBuilder.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeroscapeBuilder.Server.Data.Migrations
{
    [DbContext(typeof(HsbDbContext))]
    [Migration("20241025151129_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.ArmyCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("AdvAttack")
                        .HasColumnType("bigint");

                    b.Property<long?>("AdvDefense")
                        .HasColumnType("bigint");

                    b.Property<long?>("AdvMove")
                        .HasColumnType("bigint");

                    b.Property<long?>("AdvRange")
                        .HasColumnType("bigint");

                    b.Property<long?>("BasicAttack")
                        .HasColumnType("bigint");

                    b.Property<long?>("BasicDefense")
                        .HasColumnType("bigint");

                    b.Property<long?>("BasicMove")
                        .HasColumnType("bigint");

                    b.Property<long?>("BasicRange")
                        .HasColumnType("bigint");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("General")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Life")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Planet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Points")
                        .HasColumnType("bigint");

                    b.Property<string>("Race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rarity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Set")
                        .HasColumnType("bigint");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("SizeCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("army_card_pkey");

                    b.HasIndex("Creator");

                    b.HasIndex("Set");

                    b.ToTable("army_card", null, t =>
                        {
                            t.HasComment("A list of stats and abilities for each unit in Heroscape");
                        });
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.ArmyCardAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ability");

                    b.Property<string>("AbilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ability_name");

                    b.Property<int>("ArmyCardId")
                        .HasColumnType("int")
                        .HasColumnName("army_card_id");

                    b.HasKey("Id")
                        .HasName("army_card_abilites_pkey");

                    b.HasIndex("ArmyCardId");

                    b.ToTable("army_card_abilities", (string)null);
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.ArmyCardFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ArmyCardId")
                        .HasColumnType("int")
                        .HasColumnName("army_card_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_path");

                    b.Property<string>("FilePurpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_purpose");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent");

                    b.HasKey("Id")
                        .HasName("army_card_files_pkey");

                    b.HasIndex("ArmyCardId");

                    b.HasIndex("ParentId");

                    b.ToTable("army_card_files", (string)null);
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.Creator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatorName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Creator");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id", "CreatorName")
                        .HasName("Creator_pkey");

                    b.HasIndex(new[] { "CreatorName" }, "Creator_Creator_key")
                        .IsUnique();

                    b.ToTable("creator", (string)null);
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.Set", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("Heroscape")
                        .HasColumnName("creator");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<long?>("UnitsInSet")
                        .HasColumnType("bigint")
                        .HasColumnName("units_in_set");

                    b.Property<string>("Wave")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("wave");

                    b.HasKey("Id")
                        .HasName("set_pkey");

                    b.HasIndex("Creator");

                    b.ToTable("set", (string)null);
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.SetTerrain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint")
                        .HasColumnName("quantity");

                    b.Property<long>("Set")
                        .HasColumnType("bigint")
                        .HasColumnName("set");

                    b.Property<long>("Terrain")
                        .HasColumnType("bigint")
                        .HasColumnName("terrain");

                    b.HasKey("Id")
                        .HasName("set_terrain_pkey");

                    b.HasIndex("Set");

                    b.HasIndex("Terrain");

                    b.ToTable("set_terrain", (string)null);
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.Terrain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short?>("Hexes")
                        .HasColumnType("smallint")
                        .HasColumnName("hexes");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("terrain_pkey");

                    b.ToTable("terrain", (string)null);
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.ArmyCard", b =>
                {
                    b.HasOne("HeroscapeBuilder.Server.Data.Entities.Creator", "CreatorNavigation")
                        .WithMany("ArmyCards")
                        .HasForeignKey("Creator")
                        .HasPrincipalKey("CreatorName")
                        .IsRequired()
                        .HasConstraintName("army_card_Creator_fkey");

                    b.HasOne("HeroscapeBuilder.Server.Data.Entities.Set", "SetNavigation")
                        .WithMany("ArmyCards")
                        .HasForeignKey("Set")
                        .HasConstraintName("army_card_Set_fkey");

                    b.Navigation("CreatorNavigation");

                    b.Navigation("SetNavigation");
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.ArmyCardAbility", b =>
                {
                    b.HasOne("HeroscapeBuilder.Server.Data.Entities.ArmyCard", "ArmyCard")
                        .WithMany("ArmyCardAbilities")
                        .HasForeignKey("ArmyCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("army_card_abilities_army_card_id_fkey");

                    b.Navigation("ArmyCard");
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.ArmyCardFile", b =>
                {
                    b.HasOne("HeroscapeBuilder.Server.Data.Entities.ArmyCard", "ArmyCard")
                        .WithMany("ArmyCardFiles")
                        .HasForeignKey("ArmyCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("army_card_files_army_card_id_fkey");

                    b.HasOne("HeroscapeBuilder.Server.Data.Entities.ArmyCardFile", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("army_card_files_parent_fkey");

                    b.Navigation("ArmyCard");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.Set", b =>
                {
                    b.HasOne("HeroscapeBuilder.Server.Data.Entities.Creator", "CreatorNavigation")
                        .WithMany("Sets")
                        .HasForeignKey("Creator")
                        .HasPrincipalKey("CreatorName")
                        .IsRequired()
                        .HasConstraintName("set_creator_fkey");

                    b.Navigation("CreatorNavigation");
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.SetTerrain", b =>
                {
                    b.HasOne("HeroscapeBuilder.Server.Data.Entities.Set", "SetNavigation")
                        .WithMany("SetTerrains")
                        .HasForeignKey("Set")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("set_terrain_set_fkey");

                    b.HasOne("HeroscapeBuilder.Server.Data.Entities.Terrain", "TerrainNavigation")
                        .WithMany("SetTerrains")
                        .HasForeignKey("Terrain")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("set_terrain_terrain_fkey");

                    b.Navigation("SetNavigation");

                    b.Navigation("TerrainNavigation");
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.ArmyCard", b =>
                {
                    b.Navigation("ArmyCardAbilities");

                    b.Navigation("ArmyCardFiles");
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.ArmyCardFile", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.Creator", b =>
                {
                    b.Navigation("ArmyCards");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.Set", b =>
                {
                    b.Navigation("ArmyCards");

                    b.Navigation("SetTerrains");
                });

            modelBuilder.Entity("HeroscapeBuilder.Server.Data.Entities.Terrain", b =>
                {
                    b.Navigation("SetTerrains");
                });
#pragma warning restore 612, 618
        }
    }
}
